services:
  whisperlivekit:
    build:
      context: .
      args:
        EXTRAS: diarization
        HF_TKN_FILE: hf_token.txt
    container_name: whisperlivekit
    ports:
      - "8000:8000"
    volumes:
      - ./whisperlivekit:/app/whisperlivekit # mount only whisperlivekit but don't overwrite dependencies (pip install -e)
      - ./test:/app/test
      - /mnt/d/MEGAN/data:/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["whisperlivekit-server", "--host", "0.0.0.0", "--model", "base", "--log-level", "INFO", "--vac"] #, "--diarization"]

